### ISSUE TITLE
Use a different location picker dialog

### ISSUE THREAD

**Issue by Torniojaws** [markheath/midifilemapper#2]
Been using this tool since 2008 :) Thanks!

What I would hope - if the project is still active - is to have the more "traditional" file save dialog, similar to this one, in Step 4:

![image](https://user-images.githubusercontent.com/5442750/45257301-90ce8300-b3ac-11e8-91ac-c447f39efb0c.png)

Instead of the File tree dialog.

**Comment by markheath** [comment]
The reason it uses the dialog it does is that you are picking a folder not a file. You can't use the regular save dialog to pick a folder unfortunately
